Fix length header with UTF8 content
getsentry/develop pull request #186
Opened 2020-10-27 15:48 UTC by Tyrrrz

"\xef\xbb\xbfHello\r\n\n" has length of 11 as a string (or 10 if you don't count the last \n), but is actually 14 (or 13) bytes in UTF8

2020-10-27 15:48 UTC, Tyrrrz commented
cc @bruno-garcia

2020-10-29 01:53 UTC, bruno-garcia approved these changes
Makes sense to me.

2020-10-29 01:55 UTC, bruno-garcia commented
Makes sense to me (it's also what the counting bytes in C# says) but tagging @HazAT and @Swatinem to confirm from their side if there's no misunderstanding here

2020-10-29 07:22 UTC, Swatinem requested changes
I count 10 bytes. This is not really about utf-8. As the paragraph above says, this is only about the notation.

2020-10-29 07:22 UTC, Swatinem commented on src/docs/sdk/envelopes.mdx
>  \xef\xbb\xbfHello\r\n\n
```
\xef\xbb\xbfHello\r\n\n
|   |   |   |||||| | <
1   2   3   456789 10<
```

2020-10-29 07:23 UTC, Swatinem commented
Also open the browser console real quick: `"\xef\xbb\xbfHello\r\n".length == 10`

2020-10-30 00:21 UTC, bruno-garcia commented
Yeah that makes sense

2020-10-30 00:21 UTC, closed without merging

2020-10-30 00:22 UTC, bruno-garcia commented
Thanks @Swatinem