ref(sdk-breadcrumbs): Add Breadcrumb timestamp info
getsentry/develop pull request #205
Opened 2020-11-12 13:50 UTC by priscilawebdev

Related to the PR https://github.com/getsentry/sentry/issues/8133

2020-11-13 09:17 UTC, HazAT requested changes

2020-11-13 09:17 UTC, HazAT commented on src/docs/sdk/event-payloads/breadcrumbs.mdx
> +  Timestamp is for information only and does not change the order in which the breadcrumbs are displayed in the UI.
```suggestion
  Breadcrumbs will not be sorted by timestamp, they keep their order in the way they were added.
```

2020-11-16 10:59 UTC, kamilogorek approved these changes

2020-11-16 11:01 UTC, HazAT approved these changes

2020-11-16 11:03 UTC, merged